let juegos = [
    {
      popularity: 93.841,
      vote_count: 166,
      video: false,
      poster_path: "../img/pc1.jpg",
      id: 3498,
      adult: false,
      backdrop_path: "../img/pc1.jpg",
      original_language: "en",
      original_title: "Grand Theft Auto V",
      genre_ids: [28, 18, 36, 10752],
      title: "Grand Theft Auto V",
      vote_average: 4.48,
      overview:
        "Grand Theft Auto cuenta la historia de distintos criminales y aunque sean varios, por una razón se van relacionando y envolviendo en problemas a más personajes conforme va pasando el tiempo. Generalmente los protagonistas son antihéroes.",
      release_date: "2013-09-17",
      precio:"15",
    },
    {
      popularity: 75.527,
      vote_count: 1276,
      video: false,
      poster_path: "../img/pc2.jpg",
      id: 4200,
      adult: false,
      backdrop_path: "../img/pc2.jpg",
      original_language: "en",
      original_title: "Portal 2",
      genre_ids: [12, 16, 35, 9648, 10751],
      title: "Portal 2",
      vote_average: 4.62,
      overview:
        'Tras los eventos del primer Portal, Chell (nuestra protagonista) despierta 50 días después de haber sido criogenizada en lo que parece ser una habitación de hotel, donde una máquina alternativa le da una serie de indicaciones para moverse y finalmente volver a dormir. Posteriormente Chell es despertada de nuevo, pero esta vez la habitación donde se encuentra está seriamente deteriorada, con el contador de tiempo fallando. De fondo suena una voz al otro lado de la puerta, tras abrirla aparece Wheatley, el módulo de personalidad que despertó a Chell de su letargo.',
      release_date: "2011-04-18",
      precio:"15",
    },
    {
      popularity: 71.584,
      vote_count: 656,
      video: false,
      poster_path: "../img/pc3.jpg",
      id: 3328,
      adult: false,
      backdrop_path: "../img/pc3.jpg",
      original_language: "en",
      original_title: "The Witcher 3: Wild Hunt",
      genre_ids: [12, 14, 878, 10751],
      title: "The Witcher 3: Wild Hunt ",
      vote_average: 4.68,
      overview:
        "La historia se centra en el personaje Geralt de Rivia, quien recibe una carta de su amante Yennefer de Vengerberg diciendo que necesita localizarlo lo antes posible. Geralt, después de encontrar a su amante, aprende que Ciri, nieta de Calenthe y exalumna del mismo personaje, es buscada por La Cacería Salvaje, un grupo antiguo de espectros que están liderados por el Rey de La Cacería Salvaje. Tras varios sucesos que llevan al personaje principal a buscar a Ciri en la gran ciudad de Novigrado, en las Islas Skellige y en las tierras de Velen, Geralt, aprende que La Cacería Salvaje, busca una manera de que se cumpla la Profecía de Ithlinne, la cual dice que el universo será destruido por el Frío Blanco. Ciri, debido a que es hija de la sangre vieja, es la única que puede destruir esta profecía y salvar al mundo",
      release_date: "2020-06-12",
      precio:"15",
    },
    {
      popularity: 67.007,
      vote_count: 4,
      video: false,
      poster_path: "../img/pc4.jpg",
      id: 5286,
      adult: false,
      backdrop_path: "../img/pc4.png",
      original_language: "es",
      original_title: "Tomb Raider (2013)",
      genre_ids: [28, 35],
      title: "Tomb Raider (2013)",
      vote_average: 4.06,
      overview:
        'El juego transcurre en Yamatai, una isla del Triángulo del Dragón, en la costa de Japón. La isla y el reino que una vez existieron es un misterio, debido a las tormentas y corrientes marítimas que la rodean. Yamatai fue gobernada por la Reina del Sol, llamada Himiko, quien, acorde a la leyenda, tenía poderes místicos que la permitían controlar el tiempo atmosférico. Se sabe poco acerca de la historia de Yamatai desde que Himiko murió. Explorando la isla, el jugador descubre muchas otras culturas que llegaron a la isla, como comerciantes portugueses del siglo XVI, miembros del Cuerpo de Marines de los Estados Unidos y un proyecto militar de los japoneses durante la Segunda Guerra Mundial. Al comienzo del juego, la isla está habitada únicamente por los Solarii, una secta violenta liderada por el Padre Mathias, creada con el propósito de adorar y traer de regreso a la Reina del Sol.',
      release_date: "2013-03-05",
    },
    {
      popularity: 65.872,
      vote_count: 6,
      video: false,
      poster_path: "../img/pc5.jpg",
      id: 5679,
      adult: false,
      backdrop_path: "../img/pc5.jpg",
      original_language: "ko",
      original_title: "The Elder Scrolls V: Skyrim",
      genre_ids: [28, 27, 53],
      title: "The Elder Scrolls V: Skyrim",
      vote_average: 4.42,
      overview:
        "Skyrim tiene lugar doscientos años después de lo ocurrido en Oblivion,3​ por lo que no es una continuación o secuela. El juego se asienta en los terrenos de la provincia de Skyrim, que se encuentra en plena guerra civil fratricida entre dos facciones enfrentadas política y militarmente: «Los capas de la tormenta» que agrupa a la raza «nórdica» autóctona de Skyrim de un lado, y del otro «El Imperio de Cyrodiil",
      release_date: "2011-11-11",
    },
    {
      popularity: 64.659,
      vote_count: 2,
      video: false,
      poster_path: "../img/pc6.jpg",
      id: 5680,
      adult: false,
      backdrop_path: "../img/pc6.jpg",
      original_language: "en",
      original_title: "DOOM ETERNAL",
      genre_ids: [18, 27],
      title: "DOOM ETERNAL",
      vote_average: 8.2,
      overview:
        "Las fuerzas del Inframundo han comenzado a invadir la Tierra, y mientras la Corporación Aerospacial de la Unión lucha por defenderla, ponte en la piel del Slayer y enfrenta a nuevos enemigos infernales los cuales no temen a nada, salvo a ti",
      release_date: "2020-07-03",
    },
    {
      popularity: 64.157,
      vote_count: 2595,
      video: false,
      poster_path: "../img/pc7.jpg",
      id: 508439,
      adult: false,
      backdrop_path: "../img/pc7.jpg",
      original_language: "en",
      original_title: "PES 2020",
      genre_ids: [12, 16, 35, 14, 10751],
      title: "PES 2020",
      vote_average: 7.9,
      overview:
        "eFootball Pro Evolution Soccer 2020 (oficialmente abreviado eFootball PES 2020, también llamado eFootball Winning Eleven 2020 en Japón) es un videojuego de simulación de fútbol desarrollado por PES Productions y publicado por Konami",
      release_date: "2020-02-29",
    },
    {
      popularity: 60.08,
      vote_count: 6,
      video: false,
      poster_path: "../img/pc8.jpg",
      id: 608195,
      adult: false,
      backdrop_path: "../img/pc8.jpg",
      original_language: "en",
      original_title: "Dying Light",
      genre_ids: [14, 27, 53, 10752],
      title: "Dying Light",
      vote_average: 4.3,
      overview:
        "Dying Light es un juego de acción en primera persona del género Horror de supervivencia, el cual se desarrolla durante un apocalipsis zombie",
      release_date: "2020-07-03",
    },
    {
      popularity: 49.873,
      vote_count: 205,
      video: false,
      poster_path: "../img/pc9.jpg",
      id: 706510,
      adult: false,
      backdrop_path: "../img/pc9.jpg",
      original_language: "en",
      original_title: "BioShock",
      genre_ids: [35, 10749],
      title: "BioShock",
      vote_average: 6.4,
      overview:
        "El juego transcurre en una ucronía del año 1960, y pone al jugador en el rol de Jack, superviviente de un accidente de avión, que luego deberá explorar la ciudad de Rapture, mientras que lucha contra seres humanos mutados con poderes especiales y robots diseñados para atacar ciertos objetivos automáticamente",
      release_date: "2020-07-03",
    },
    {
      popularity: 44.469,
      vote_count: 1097,
      video: false,
      poster_path: "../img/pc10.jpg",
      id: 514847,
      adult: false,
      backdrop_path: "../img/pc10.jpg",
      original_language: "en",
      original_title: "Resident Evil 7 ",
      genre_ids: [28, 27, 53],
      title: "Resident Evil 7 ",
      vote_average: 6.7,
      overview:
        '  Ethan es capturado por Jack y llevado a la mansión Baker, mientras esta inconsciente, Zoe Baker le devuelve su mano engrapandola y curandola con un líquido especial, luego se marcha. Al anochecer Ethan es llevado a una macabra cena familiar (homenaje a la película la masacre de Texas), allí están la esposa de Jack, Marguerite, su hijo Lucas y una anciana en silla de ruedas.',
      release_date: "2020-03-11",
    },
    {
      popularity: 43.668,
      vote_count: 218,
      video: false,
      poster_path: "../img/pc11.jpg",
      id: 592350,
      adult: false,
      backdrop_path: "../img/pc11.jpg",
      original_language: "ja",
      original_title: "Red Dead Redemption 2",
      genre_ids: [28, 16],
      title: "Red Dead Redemption 2",
      vote_average: 8.9,
      overview:
        'Red Dead Redemption 2 es un videojuego de acción-aventura western, en un mundo abierto y en perspectiva de primera y tercera persona con componentes para un jugador y multijugador. Fue desarrollado por Rockstar Games. Es la precuela de Red Dead Redemption y el tercer juego de la saga Red Dead.',
      release_date: "2019-12-20",
      precio:"15",
    },
    {
      popularity: 41.788,
      vote_count: 17409,
      video: false,
      poster_path: "../img/pc12.jpg",
      id: 603,
      adult: false,
      backdrop_path: "../img/pc12.jpg",
      original_language: "en",
      original_title: "Ghost Of a Tale ",
      genre_ids: [28, 878],
      title: "Ghost Of a Tale ",
      vote_average: 8.1,
      overview:
        "Ghost of a Tale tiene lugar en un mundo medieval habitado por varias especies de animales antropomórficos , muchos de los cuales habitan en su propio reino: la tradición incluye ratones, ratas, ranas, cangrejos, tejones, halcones, arañas, sanguijuelas, urracas y varias criaturas no muertas.",
      release_date: "1999-03-30",
      precio:"15",
    },
    {
      popularity: 41.311,
      vote_count: 64,
      video: false,
      poster_path: "../img/pc13.jpg",
      id: 602147,
      adult: false,
      backdrop_path: "../img/pc13.jpg",
      original_language: "en",
      original_title: "Tekken 7",
      genre_ids: [18, 9648, 53],
      title: "Tekken 7",
      vote_average: 5.9,
      overview:
        "Tekken 7 (鉄拳7?) es un videojuego de lucha desarrollado y distribuido por Namco Bandai Games. El juego es la séptima entrega principal de la saga Tekken y el primero en utilizar el motor gráfico Unreal Engine..",
      release_date: "2020-04-30",
    },
    {
      popularity: 40.241,
      vote_count: 23,
      video: false,
      poster_path: "../img/pc14.jpg",
      id: 606234,
      adult: false,
      backdrop_path: "../img/pc14.jpg",
      original_language: "en",
      original_title: "Alien Isolation",
      genre_ids: [878],
      title: "Alien Isolation",
      vote_average: 5.8,
      overview:
        "Alien: Isolation es un videojuego de horror de supervivencia y sigilo en primera persona2​ desarrollado por The Creative Assembly y publicado por Sega",
      release_date: "2014-10-07",
    },
    {
      popularity: 38.96,
      vote_count: 415,
      video: false,
      poster_path: "../img/pc15.jpg",
      id: 531454,
      adult: false,
      backdrop_path: "../img/pc15.jpg",
      original_language: "en",
      original_title: "Blair Witch",
      genre_ids: [35, 10402],
      title: "Blair Witch",
      vote_average: 6.5,
      overview:
        "s un juego de terror en primera persona que se desarrolla en el universo del Proyecto de la bruja de Blair. Nos invita a adentrarnos en un bosque aterrador, con la única compañía de nuestro perro, una linterna y por supuesto, una cámara de vídeo.",
      release_date: "2019-10-30",
    },
    {
      popularity: 38.563,
      id: 686245,
      video: false,
      vote_count: 20,
      vote_average: 5.9,
      title: "outlast 2 ",
      release_date: "2017-04-24",
      original_language: "en",
      original_title: "outlast 2 ",
      genre_ids: [28, 53],
      backdrop_path: "../img/pc16.jpg",
      adult: false,
      overview:
        " Outlast 2 es un videojuego de horror de supervivencia en primera persona desarrollado y publicado por Red Barrels Games. Es la secuela del videojuego de 2013 Outlast, y cuenta con un periodista llamado Blake Langermann, junto con su esposa Lynn, vagando por el desierto de Arizona para explorar el asesinato de una mujer embarazada",
      poster_path: "../img/pc16.jpg",
    },
    {
      popularity: 38.326,
      vote_count: 115,
      video: false,
      poster_path: "../img/pc17.jpg",
      id: 451184,
      adult: false,
      backdrop_path: "../img/pc17.jpg",
      original_language: "en",
      original_title: "Mortal Kombat 11 ",
      genre_ids: [18, 36, 53],
      title: "Mortal Kombat 11 ",
      vote_average: 6.3,
      overview:
        "Mortal Kombat 11 es un videojuego de lucha desarrollado por NetherRealm Studios y publicado por Warner Bros. Interactive Entertainment. Se ejecuta en una versión muy modificada de Unreal Engine 3, ​ es la undécima entrega principal de la serie Mortal Kombat y una secuela de 2015 Mortal Kombat X",
      release_date: "2019-03-23",
    },
    {
      popularity: 38.129,
      vote_count: 74,
      video: false,
      poster_path: "../img/pc18.jpg",
      id: 619592,
      adult: false,
      backdrop_path: "../img/pc18.jpg",
      original_language: "en",
      original_title: "Shadow of the Tomb Raider ",
      genre_ids: [28, 18],
      title: "Shadow of the Tomb Raider",
      vote_average: 5.4,
      overview:
        "La introducción del juego comienza en la ciudad de Cozumel, México, donde Lara busca pistas para encontrar un objeto mítico a través de información que oculta La Trinidad, y es cuando la encuentran, donde termina la introducción y se sigue con la historia principal.",
      release_date: "2019-11-05",
    },
    {
      popularity: 36.705,
      vote_count: 1972,
      video: false,
      poster_path: "../img/pc19.jpg",
      id: 522938,
      adult: false,
      backdrop_path: "../img/pc19.jpg",
      original_language: "en",
      original_title: "Gears of War 5 ",
      genre_ids: [28, 18, 53],
      title: "Gears of War 5 ",
      vote_average: 6.3,
      overview:
        "Gears 5 se centra en Kait Díaz (Laura Bailey), una forastera de ascendencia Locust. Como Kait, el jugador debe descubrir los orígenes del Enjambre (Swarm) y la familia de Kait. El protagonista JD Fenix (Liam McIntyre), su amigo Delmont Walker (Eugene Byrd), y el padre de JD Marcus Fenix. (John DiMaggio) también regresan en esta quinta entrega",
      release_date: "2019-09-10",
    },
    {
      popularity: 36.35,
      vote_count: 3,
      video: false,
      poster_path: "../img/pc20.jpg",
      id: 625568,
      adult: false,
      backdrop_path: "../img/pc20.jpg",
      original_language: "en",
      original_title: "Darksiders Wrath of War",
      genre_ids: [53],
      title: "Darksiders Wrath of War",
      vote_average: 8.3,
      overview: "Desde el inicio, ha habido una lucha entre las fuerzas del Cielo y las del Infierno. Como moderadores, surgió el Consejo abrasado. Cuando las reglas no se cumplían, los cuatro Jinetes del Apocalipsis son invocados para castigar a quienes no las cumplen",
      release_date: "2020-07-16",
    },
  ];
  