let ps2 = [
    {
      popularity: 9.53,
      vote_count: 166,
      video: false,
      poster_path: "../img/ps21.jpg",
      id: 3498,
      adult: false,
      backdrop_path: "../img/ps21.jpg",
      original_language: "en",
      original_title: "Metal Gear Solid 3 Snake Eater",
      genre_ids: [28, 18, 36, 10752],
      title: "Metal Gear Solid 3 Snake Eater",
      vote_average: 9.53,
      overview:
        "Esta secuela de Metal Gear nos cuenta la historia de Big Boss, el soldado del que Solid Snake y Liquid Snake son clones, en una operación en Rusia para investigar los planes del enemigo comunista, germen de los Metal Gear. Conocidos como Revolver Ocelot aparecen en una historia llena de giros y traiciones que es la base de toda la historia de la saga.",
      release_date: "2004-11-17",
      precio:"15",
    },
    {
      popularity: 9.46,
      vote_count: 1276,
      video: false,
      poster_path: "../img/ps22.jpg",
      id: 4200,
      adult: false,
      backdrop_path: "../img/ps22.jpg",
      original_language: "en",
      original_title: "Grand Theft Auto San Andreas",
      genre_ids: [12, 16, 35, 9648, 10751],
      title: "Grand Theft Auto San Andreas",
      vote_average: 9.46,
      overview:
        'El GTA definitivo para PlayStation 2 lleva la acción a la zona de California y Las Vegas de los años 90, en una aventura en la que Carl Johnson, natural de Los Santos (Los Ángeles), tendrá que limpiar su nombre en su ciudad, en San Fierro (San Francisco), Las Venturas (Las Vegas) y en todo el interior del estado de San Andreas.',
      release_date: "2014-10-26",
      precio:"15",
    },
    {
      popularity: 9.44,
      vote_count: 656,
      video: false,
      poster_path: "../img/ps23.jpg",
      id: 3328,
      adult: false,
      backdrop_path: "../img/ps23.jpg",
      original_language: "en",
      original_title: "Shadow of the Colossus",
      genre_ids: [12, 14, 878, 10751],
      title: "Shadow of the Colossus ",
      vote_average: 9.44,
      overview:
        "La secuela espiritual de Ico, creada por sus mismos autores, nos lleva a un mundo casi sin vida, vacío, en el que tendremos que derrotar a dieciséis colosos que primero tendremos que encontrar. A lomos de nuestro caballo, tendremos que orientarnos con nuestra espada, que indica con luz hacia dónde se encuentra el siguiente enemigo, y cuando nos enfrentemos a los gigantescos colosos tendremos que identificar sus habilidades y aprovecharnos de ellas para vencerlos.",
      release_date: "2005-10-18",
      precio:"15",
    },
    {
      popularity: 9.35,
      vote_count: 9.35,
      video: false,
      poster_path: "../img/ps24.jpg",
      id: 5286,
      adult: false,
      backdrop_path: "../img/ps24.jpg",
      original_language: "es",
      original_title: "God of War 2: Divine Retribution ",
      genre_ids: [28, 35],
      title: "God of War 2: Divine Retribution ",
      vote_average: 9.35,
      overview:
        'Después de ser repudiado por el dios Zeus, Kratos, el nuevo Dios de la Guerra, pierde el favor y reconocimiento del Olimpo. Con una brutalidad que ya es santo y seña de su personalidad y la sed de venganza después de esta decisión, nuestro protagonista inicia un viaje con el que vengarse y desquitarse de todos estos hechos. Un trabajo mitológico de gran envergadura que nos pondrá delante de las criaturas más peligrosas en la secuela de uno de los títulos más esperados de PlayStation 2.',
      release_date: "2007-03-13",
    },
    {
      popularity: 9.33,
      vote_count: 9.33,
      video: false,
      poster_path: "../img/ps25.jpg",
      id: 5679,
      adult: false,
      backdrop_path: "../img/ps25.jpg",
      original_language: "ko",
      original_title: "Burnout 3 Takedown ",
      genre_ids: [28, 27, 53],
      title: "Burnout 3 Takedown ",
      vote_average: 9.33,
      overview:
        "Burnout 3: Takedown es un videojuego de carreras desarrollado por Criterion Studios y distribuido por Electronic Arts que salió a la venta el 18 de septiembre de 2004 para las plataformas Xbox y PlayStation 2. Es la tercera entrega de la saga Burnout, y la primera en ser distribuida por EA Games tras el cierre de Acclaim, estando este más cuidado en cuanto a gráficos y sonido",
      release_date: "2004-09-18",
    },
    {
      popularity: 9.26,
      vote_count:9.26,
      video: false,
      poster_path: "../img/ps26.jpg",
      id: 5680,
      adult: false,
      backdrop_path: "../img/ps26.jpg",
      original_language: "en",
      original_title: "Metal Gear Solid 2: Sons of Liberty ",
      genre_ids: [18, 27],
      title: "Metal Gear Solid 2: Sons of Liberty ",
      vote_average: 9.26,
      overview:
        "Años después de los sucesos de Metal Gear Solid, en Shadow Moses, el agente Raiden tiene que infiltrarse en una planta de limpieza que ha sido atacada por un grupo terrorista dirigido por Revolver Ocelot y Solidus Snake. Para ello contará con la ayuda de Solid Snake.",
      release_date: "2001-11-13",
    },
    {
      popularity: 9.24,
      vote_count: 9.24,
      video: false,
      poster_path: "../img/ps27.jpg",
      id: 508439,
      adult: false,
      backdrop_path: "../img/ps27.jpg",
      original_language: "en",
      original_title: "Ico ",
      genre_ids: [12, 16, 35, 14, 10751],
      title: "Ico ",
      vote_average: 9.24,
      overview:
        "Un juego misterioso y una de las mayores obras de arte digital de su tiempo. Nuestro pequeño héroe tendrá que salvar a una misteriosa princesa de las huestes de la oscuridad, acompañándola por todo tipo de imaginativos niveles en un mundo perdido.",
      release_date: "2004-09-24",
    },
    {
      popularity: 9.15,
      vote_count: 9.15,
      video: false,
      poster_path: "../img/ps28.jpg",
      id: 608195,
      adult: false,
      backdrop_path: "../img/ps28.jpg",
      original_language: "en",
      original_title: "Resident Evil 4",
      genre_ids: [14, 27, 53, 10752],
      title: "Resident Evil 4",
      vote_average: 9.15,
      overview:
        "Leon Kennedy, protagonista de Resident Evil 2, viaja a España para hacer frente a oleadas de infectados en PS2, en una cuarta parte que tiene más acción que los primeros juegos, una perspectiva sobre el hombro, y una historia que nos irá sumergiendo poco a poco.",
      release_date: "2005-01-11",
    },
    {
      popularity:9.14,
      vote_count: 9.14,
      video: false,
      poster_path: "../img/ps29.jpg",
      id: 706510,
      adult: false,
      backdrop_path: "../img/ps29.jpg",
      original_language: "en",
      original_title: "God of War (2005) ",
      genre_ids: [35, 10749],
      title: "God of War (2005) ",
      vote_average: 9.14,
      overview:
        "God of War es uno de los más espectaculares y frenéticos juegos de acción en PlayStation 2. Recogiendo el testigo de títulos como Devil May Cry, nos lleva a una antigua Grecia sumida en el caos entre atenieses, persas y la ira de los antiguos dioses. Nosotros seremos Kratos, un general espartano que ha ejercido de soldado de los dioses, pero que ahora se revela contra ellos. Acción frenética y algún que otro puzle en uno de los juegos de acción con mayúsculas de PS2.",
      release_date: "2020-07-03",
    },
    {
      popularity: 9.1,
      vote_count:9.1,
      video: false,
      poster_path: "../img/ps210.jpg",
      id: 514847,
      adult: false,
      backdrop_path: "../img/ps210.jpg",
      original_language: "en",
      original_title: "Silent Hill 2",
      genre_ids: [28, 27, 53],
      title: "Silent Hill 2 ",
      vote_average: 9.12,
      overview:
        'Silent Hill 2 es la secuela del videojuego con el mismo nombre realizada por Konami. La historia del juego devuelve al jugador a Silent Hill, un espacio renovado completamente en lo gráfico que mejora ostensiblemente a su antecesor. A este trabajo técnico lo acompaña una nueva historia que confundirá al jugador manteniendo la jugabilidad del primero. Grandes dosis de terror y miedo que obligarán al jugador a avanzar de la mano de James Sunderland, que investiga una misteriosa carta.',
      release_date: "2001-09-24",
    },
    {
      popularity: 43.668,
      vote_count: 218,
      video: false,
      poster_path: "../img/ps211.jpg",
      id: 592350,
      adult: false,
      backdrop_path: "../img/ps211.jpg",
      original_language: "ja",
      original_title: "Metal Gear Solid 3 Snake Eater",
      genre_ids: [28, 16],
      title: "Metal Gear Solid 3 Snake Eater",
      vote_average: 9.1,
      overview:
        ' Metal Gear Solid 3: Subsistence es una versión de Snake Eater, el quinto episodio de la famosa saga de acción y aventura de Hideo Kojima. El juego también incluye un nuevo modo online, las versiones de MGS de MSX, una cámara diferente y diferente extras que llegan al mercado nacional en lo que es un homenaje a todos los seguidores. Subsistence se convierte en una reedición de gran calidad que también incluye escenas cinematográficas de su historia.',
      release_date: "2004-11-17",
      precio:"15",
    },
    {
      popularity: 41.788,
      vote_count: 17409,
      video: false,
      poster_path: "../img/ps212.jpg",
      id: 603,
      adult: false,
      backdrop_path: "../img/ps212.jpg",
      original_language: "en",
      original_title: "Final Fantasy X  ",
      genre_ids: [28, 878],
      title: "Final Fantasy X ",
      vote_average: 9,
      overview:
        "Décima entrega de la saga Final Fantasy y primera para PlayStation 2, ambientada en un mundo futurista y protagonizada por Tidus, la estrella de un deporte llamado Blitzball, que vive en la ciudad de Zanarkand. Tras el ataque de un ser mitológico llamado Sinh, su ciudad es destruída y él salvado en el último momento... y llevado mil años al futuro.",
      release_date: "2001-07-19",
      precio:"15",
    },
    {
      popularity: 41.311,
      vote_count: 64,
      video: false,
      poster_path: "../img/ps213.jpg",
      id: 602147,
      adult: false,
      backdrop_path: "../img/ps213.jpg",
      original_language: "en",
      original_title: "Jak 3",
      genre_ids: [18, 9648, 53],
      title: "Jak 3",
      vote_average: 8.68,
      overview:
        "ak 3 es un videojuego de plataformas de acción-aventura desarrollado por Naughty Dog y distribuido por Sony Computer Entertainment. El título, precedido por Jak II, es el tercer juego de la serie Jak and Daxter. Fue lanzado en Norteamérica el 9 de noviembre de 2004 y en Europa el 26 de noviembre de 2004",
      release_date: "2004-11-09",
    },
    {
      popularity: 40.241,
      vote_count: 23,
      video: false,
      poster_path: "../img/ps214.jpg",
      id: 606234,
      adult: false,
      backdrop_path: "../img/ps214.jpg",
      original_language: "en",
      original_title: "Final Fantasy XII",
      genre_ids: [878],
      title: "Final Fantasy XII",
      vote_average: 8.94,
      overview:
        "Este es el último título de la saga Final Fantasy para PlayStation 2 y vuelve al RPG de siempre después de su exploración en el modo online. Una historia potente y un sistema de combate muy cambiado son el sello que Square Enix ha querido para esta gran entrega. El juego aporta un toque fresco y novedoso siendo siempre fiel a Final Fantasy. La herencia de los trabajos anteriores de Yasumi Matsuno e Hiroshi Minagawa se nota en cada uno de los gráficos.",
      release_date: "2006-03-16",
    },
    {
      popularity: 38.96,
      vote_count: 415,
      video: false,
      poster_path: "../img/ps215.jpg",
      id: 531454,
      adult: false,
      backdrop_path: "../img/ps215.jpg",
      original_language: "en",
      original_title: "Devil May Cry ",
      genre_ids: [35, 10402],
      title: "Devil May Cry ",
      vote_average: 8.81,
      overview:
        "El mundo del videojuego tiene un nuevo héroe de acción: Dante, un cazador de demonios, hijo de Sparda, que lucha contra el mal para vengar la muerte de su madre. Devil May Cry nos lleva a enormes escenarios de inspiración gótica y barroca, planteándonos luchas salvajes contra demonios de todos los tamaños, así como partes de plataformas y algunos puzles. Uno de los juegos más impresionantes de su época, que inspiró a muchos otros juegos de acción salvaje.",
      release_date: "2001-08-23",
    },
    {
      popularity: 38.563,
      id: 686245,
      video: false,
      vote_count: 20,
      vote_average:8.83,
      title: "Tekken 5",
      release_date: "2004-02-24",
      original_language: "en",
      original_title: "Tekken 5",
      genre_ids: [28, 53],
      backdrop_path: "../img/ps216.jpg",
      adult: false,
      overview:
        "ekken 5 es un videojuego de lucha desarrollado y publicado por la empresa Namco en el año 2004 para las salas recreativas y en el 2005 para la PlayStation 2. Es la quinta entrega canónica, y la sexta entrega principal, en la serie de videojuegos de Tekken, marcando el décimo aniversario de la serie",
      poster_path: "../img/ps216.jpg",
    },
    {
      popularity: 38.326,
      vote_count: 115,
      video: false,
      poster_path: "../img/ps217.jpg",
      id: 451184,
      adult: false,
      backdrop_path: "../img/ps217.jpg",
      original_language: "en",
      original_title: "Beyond Good & Evil  ",
      genre_ids: [18, 36, 53],
      title: "Beyond Good & Evil  ",
      vote_average: 8.73,
      overview:
        "Beyond Good & Evil es un videojuego para GameCube, PC, Xbox, PlayStation 2, Xbox 360 y PlayStation 3 desarrollado por Ubisoft y publicado en el año 2003. Trata de las aventuras de una chica, Jade, que armada con una cámara fotográfica, intentará descubrir la verdad",
      release_date: "2003-11-11",
    },
    {
      popularity: 38.129,
      vote_count: 74,
      video: false,
      poster_path: "../img/ps218.jpg",
      id: 619592,
      adult: false,
      backdrop_path: "../img/ps218.jpg",
      original_language: "en",
      original_title: "Guitar Hero 5 ",
      genre_ids: [28, 18],
      title: "Guitar Hero 5 ",
      vote_average: 5.4,
      overview:
        "Guitar Hero 5 es la quinta edición de las series de videojuegos Guitar Hero, en la cual se pueden encontrar 85 temas nuevos de 83 artistas. Fue lanzado el 1 de septiembre de 2009 en Norteamérica, el 18 de septiembre de 2009 en Europa y el 16 de septiembre de 2009 en Australia y Asia",
      release_date: "2009-09-16",
    },
    {
      popularity: 36.705,
      vote_count: 1972,
      video: false,
      poster_path: "../img/ps219.jpg",
      id: 522938,
      adult: false,
      backdrop_path: "../img/ps219.jpg",
      original_language: "en",
      original_title: "Dark Chronicle ",
      genre_ids: [28, 18, 53],
      title: "Dark Chronicle ",
      vote_average:8.6,
      overview:
        "Se trata de un RPG de mazmorras protagonizado por Max y Mónica, dos jóvenes que viajarán por el tiempo que, entre sus características, incluye el georama: la construcción en el presente de ciudades que luego podemos ver en la versión del futuro.",
      release_date: "2002-11-28",
    },
    {
      popularity: 36.35,
      vote_count: 3,
      video: false,
      poster_path: "../img/ps220.jpg",
      id: 625568,
      adult: false,
      backdrop_path: "../img/ps220.jpg",
      original_language: "en",
      original_title: "Kingdom Hearts",
      genre_ids: [53],
      title: "Kingdom Hearts",
      vote_average: 8.53,
      overview: "Los mundos de Disney y de Square Enix se unen para crear un juego de acción y rol mágico. El héroe Sora tendrá que recorrer diez mundos de Disney para salvarlos, ayudándose de personajes de Disney y de Square Enix, y otros cuatro mundos completamente nuevos creados para la ocasión. Kindgom Hearts combina acción y rol, con combates de acción contra enemigos. Sora estará acompañado toda la aventura por el Pato Donald y por Goofy.",
      release_date: "2002-03-28",
    },
  ];
  